using System.Text.RegularExpressions;
using Anorath.domain.Entities;
using Anorath.Infrastructure.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Anorath.api.Controllers
{
    // What the client sends when adding/editing (the code is generated by the server)
    public record CustomerRequest(string CustomerName, string? ContactNumber, string? EmailAddress, string? Address, bool IsActive);

    [ApiController]
    [Route("customers")]
    [Authorize(Roles = "Admin,Receptionist")]
    public class CustomersController : ControllerBase
    {
        private readonly TenantErpDbContext _db;
        public CustomersController(TenantErpDbContext db) => _db = db;

        // GET customers?search=juan
        [HttpGet]
        public async Task<IActionResult> GetAll([FromQuery] string? search)
        {
            var query = _db.Customers.AsNoTracking().AsQueryable();

            if (!string.IsNullOrWhiteSpace(search))
            {
                var s = search.Trim();
                query = query.Where(c =>
                    c.CustomerCode.Contains(s) ||
                    c.CustomerName.Contains(s) ||
                    (c.ContactNumber != null && c.ContactNumber.Contains(s)) ||
                    (c.EmailAddress != null && c.EmailAddress.Contains(s)));
            }

            return Ok(await query.OrderBy(c => c.CustomerName).ToListAsync());
        }

        private static string? Validate(CustomerRequest req)
        {
            if (string.IsNullOrWhiteSpace(req.CustomerName) || req.CustomerName.Trim().Length < 2)
                return "Customer name is required (at least 2 characters).";
            if (req.CustomerName.Trim().Length > 150)
                return "Customer name is too long.";
            if (!string.IsNullOrWhiteSpace(req.ContactNumber) &&
                !Regex.IsMatch(req.ContactNumber.Trim(), @"^[0-9+\-\s]{7,20}$"))
                return "Contact number must be 7-20 digits (numbers, spaces, + or - only).";
            if (!string.IsNullOrWhiteSpace(req.EmailAddress) &&
                !Regex.IsMatch(req.EmailAddress.Trim(), @"^[^@\s]+@[^@\s]+\.[^@\s]+$"))
                return "Email address is not valid.";
            return null;
        }

        private static string? Clean(string? value) =>
            string.IsNullOrWhiteSpace(value) ? null : value.Trim();

        // Next free code: CUST-0001, CUST-0002, ...
        private async Task<string> NextCodeAsync()
        {
            var next = (await _db.Customers.MaxAsync(c => (int?)c.CustomerId) ?? 0) + 1;
            string code;
            do { code = $"CUST-{next++:0000}"; }
            while (await _db.Customers.AnyAsync(c => c.CustomerCode == code));
            return code;
        }

        [HttpPost]
        public async Task<IActionResult> Create([FromBody] CustomerRequest req)
        {
            if (Validate(req) is string error) return BadRequest(error);

            try
            {
                var customer = new Customer
                {
                    CustomerCode = await NextCodeAsync(),
                    CustomerName = req.CustomerName.Trim(),
                    ContactNumber = Clean(req.ContactNumber),
                    EmailAddress = Clean(req.EmailAddress),
                    Address = Clean(req.Address),
                    IsActive = req.IsActive
                };
                _db.Customers.Add(customer);
                await _db.SaveChangesAsync();
                return Created($"/customers/{customer.CustomerId}", customer);
            }
            catch (Exception)
            {
                return StatusCode(500, "Failed to create customer.");
            }
        }

        [HttpPut("{id:int}")]
        public async Task<IActionResult> Update(int id, [FromBody] CustomerRequest req)
        {
            var customer = await _db.Customers.FindAsync(id);
            if (customer is null) return NotFound("Customer not found.");

            if (Validate(req) is string error) return BadRequest(error);

            try
            {
                customer.CustomerName = req.CustomerName.Trim();
                customer.ContactNumber = Clean(req.ContactNumber);
                customer.EmailAddress = Clean(req.EmailAddress);
                customer.Address = Clean(req.Address);
                customer.IsActive = req.IsActive;
                await _db.SaveChangesAsync();
                return Ok(customer);
            }
            catch (Exception)
            {
                return StatusCode(500, "Failed to update customer.");
            }
        }

        [HttpDelete("{id:int}")]
        public async Task<IActionResult> Delete(int id)
        {
            var customer = await _db.Customers.FindAsync(id);
            if (customer is null) return NotFound("Customer not found.");

            // Keep booking history: customers with reservations can't be deleted
            if (await _db.Reservations.AnyAsync(r => r.CustomerId == id))
                return Conflict("This customer has reservations. Set them to Inactive instead of deleting.");

            try
            {
                _db.Customers.Remove(customer);
                await _db.SaveChangesAsync();
                return NoContent();
            }
            catch (Exception)
            {
                return StatusCode(500, "Failed to delete customer.");
            }
        }
    }
}